spring.application.name=code

#mysqlconfigs
spring.datasource.url = ${sqlurl}
spring.datasource.username=${sqlusername}
spring.datasource.password=${sqlpwd}


#hibernateconfig
spring.jpa.hibernate.ddl-auto=update

#jpaconfig
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#mongodbconfig
spring.data.mongodb.uri=${mongodburl}

#healthendpoint
management.endpoint.health.show-details=always
management.health.db.enabled=true